#!/usr/bin/php
<?php

use Egorov\Strategy\Calculator;
use Egorov\Strategy\DivideOperation;
use Egorov\Strategy\MinusOperation;
use Egorov\Strategy\MultiplyOperation;
use Egorov\Strategy\PercentOperation;
use Egorov\Strategy\PlusOperation;

require __DIR__ . '/../../vendor/autoload.php';

$firstArgument = 17;
$secondArgument = 25;

$calculator = new Calculator();

echo $calculator->setStrategy(new PlusOperation())
    ->calculate($firstArgument, $secondArgument);

echo $calculator->setStrategy(new MinusOperation())
    ->calculate($firstArgument, $secondArgument);

echo $calculator->setStrategy(new MultiplyOperation())
    ->calculate($firstArgument, $secondArgument);

echo $calculator->setStrategy(new DivideOperation())
    ->calculate($firstArgument, $secondArgument);

echo $calculator->setStrategy(new PercentOperation())
    ->calculate($firstArgument, $secondArgument);
