#!/usr/bin/php
<?php

use Egorov\Strategy\Calculator;

require __DIR__ . '/../../vendor/autoload.php';

$plusCalculator = new Calculator('+');
$subscribeCalculator = new Calculator('-');
$divideCalculator = new Calculator('/');
$multiplyCalculator = new Calculator('*');

$firstArgument = 17;
$secondArgument = 25;

echo $plusCalculator->calculate($firstArgument, $secondArgument) . "\n";
echo $subscribeCalculator->calculate($firstArgument, $secondArgument) . "\n";
echo $divideCalculator->calculate($firstArgument, $secondArgument) . "\n";
echo $multiplyCalculator->calculate($firstArgument, $secondArgument) . "\n";
